import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { startServer } from './helpers.js';

test('role based workspace, clipper privacy, reviews, analytics, exports, hover playback and mobile layout', { timeout: 120000 }, async () => {
  const server = await startServer(3112);
  let browser;
  try {
    browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'chrome', headless: true });
    const context = await browser.newContext({ baseURL: server.url, viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage();
    const errors = []; page.on('pageerror', e => { errors.push(e.message); process.stdout.write(`Browser error: ${e.message}\n`); });
    await mkdir('artifacts', { recursive: true });
    async function capture(file) {
      await page.locator('.toast').waitFor({state:'hidden'});
      await page.evaluate(() => window.scrollTo(0,0));
      await page.mouse.move(3,3);
      await page.waitForFunction(() => !document.querySelector('.page-content') || getComputedStyle(document.querySelector('.page-content')).opacity === '1');
      await page.screenshot({path:`artifacts/${file}`,fullPage:true});
    }
    async function audit(name) {
      await page.waitForFunction(() => !document.querySelector('.page-content') || getComputedStyle(document.querySelector('.page-content')).opacity === '1');
      const result = await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
      const issues=result.violations.filter(v=>['serious','critical'].includes(v.impact)).map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));
      assert.deepEqual(issues,[],`${name} accessibility`);
    }
    await page.goto(server.url);
    await page.getByRole('button',{name:'Sign in',exact:true}).waitFor();
    await capture('login-desktop.png');
    await audit('Login');
    await page.getByLabel('Email address').fill('owner@example.com');
    await page.getByLabel('Password', { exact: true }).fill('a-long-test-password');
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await page.locator('.content-desk').waitFor();
    await page.getByRole('button', { name: 'The team', exact: true }).click();
    await page.getByRole('button', { name: 'Add member', exact: true }).click();
    await page.getByLabel('Name', { exact: true }).fill('Sam');
    await page.getByLabel('Email address').fill('sam@example.com');
    await page.getByLabel('Password', { exact: true }).fill('sam-test-password');
    await page.getByRole('button', { name: 'Create member account' }).click();
    await page.getByText('Member account created. Share their login privately.').waitFor();
    assert.equal((await page.request.post('/api/team', { data: { name:'Maya', email:'maya@example.com', password:'maya-test-password', role:'team' } })).status(),201);
    await page.getByRole('button', { name: 'Sign out' }).click();
    await page.getByLabel('Email address').fill('sam@example.com');
    await page.getByLabel('Password', { exact: true }).fill('sam-test-password');
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await page.locator('.content-desk').waitFor();
    assert.equal(await page.getByRole('button', { name:'The team', exact:true }).count(),0);
    assert.equal(await page.getByRole('button', { name:'Analytics', exact:true }).count(),0);
    const video = await page.evaluate(async () => {
      const canvas = document.createElement('canvas'); canvas.width = 320; canvas.height = 480;
      const ctx = canvas.getContext('2d'); const stream = canvas.captureStream(12); const chunks = [];
      const recorder = new MediaRecorder(stream, { mimeType: 'video/webm' });
      const finished = new Promise(resolve => { recorder.ondataavailable = e => chunks.push(e.data); recorder.onstop = async () => resolve(Array.from(new Uint8Array(await new Blob(chunks).arrayBuffer()))); });
      recorder.start(); let frame = 0;
      const timer = setInterval(() => { ctx.fillStyle = '#786388'; ctx.fillRect(0, 0, 320, 480); ctx.fillStyle = '#efaf7d'; ctx.beginPath(); ctx.arc(160, 210, 65 + frame % 8, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = 'white'; ctx.font = '22px sans-serif'; ctx.fillText('TEST CLIP', 100, 340); frame++; }, 80);
      await new Promise(r => setTimeout(r, 1000)); clearInterval(timer); recorder.stop(); stream.getTracks().forEach(t => t.stop()); return finished;
    });
    const today = await page.evaluate(() => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; });
    const another = today.slice(0,8) + (today.endsWith('01') ? '02' : '01');
    for (const [title, day] of [['The perfect moment', today], ['Another day’s edit', another]]) {
      await page.getByRole('button', { name: 'Add a clip', exact: true }).first().click();
      await page.locator('input[type=file]').setInputFiles({ name: 'original.webm', mimeType: 'video/webm', buffer: Buffer.from(video) });
      await page.getByLabel('Clip title').fill(title); await page.getByLabel('Add to date').fill(day);
      await page.getByRole('button', { name: 'Add clip', exact: true }).click();
      await page.getByRole('dialog').waitFor({ state: 'hidden' });
      await page.getByRole('button', { name: title, exact: true }).waitFor();
    }
    await page.getByRole('button',{name:'All clips',exact:false}).click();
    assert.equal(await page.locator('.media-card').count(),2);
    await page.getByRole('button',{name:'By date',exact:true}).click();
    await page.getByRole('button', { name: 'Today', exact: true }).click();
    await page.getByRole('button', { name: 'The perfect moment', exact: true }).waitFor();
    const target = new Date(`${another}T12:00:00`).toLocaleDateString('en-US', { month:'long',day:'numeric',year:'numeric' });
    await page.getByRole('button', { name: `${target}, 1 clips`, exact: true }).hover();
    await page.getByRole('button', { name: 'Another day’s edit', exact: true }).waitFor();
    await page.mouse.move(10,10);
    await page.locator('.media-stage').first().hover();
    await page.waitForFunction(() => { const v=document.querySelector('.media-stage video'); return v && !v.paused && v.currentTime > 0.1; });
    await page.getByRole('button', { name: 'Unmute preview', exact: true }).click();
    assert.equal(await page.locator('.media-stage video').first().evaluate(v => v.muted), false);
    await page.getByRole('button', { name: 'Pause inline preview', exact: true }).click();
    assert.equal(await page.locator('.media-stage video').first().evaluate(v => v.paused), true);
    await page.getByRole('button', { name: 'Play inline preview', exact: true }).click();
    await page.mouse.move(10,10);
    await page.waitForFunction(() => document.querySelector('.media-stage video')?.paused);
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.mouse.move(10,10);
    await page.locator('.media-stage').first().hover();
    assert.equal(await page.locator('.media-stage video').first().evaluate(v => v.paused), true);
    await page.emulateMedia({ reducedMotion: 'no-preference' });
    await page.getByRole('button', { name: 'Another day’s edit', exact: true }).click();
    await page.locator('.preview-player').waitFor();
    await page.waitForFunction(() => document.querySelector('.preview-player')?.readyState >= 2);
    await page.getByRole('button', { name: 'Close dialog' }).click();
    const download = page.waitForEvent('download'); await page.getByRole('link', { name: 'Download original', exact: true }).click();
    const file = await download; assert.equal(file.suggestedFilename(), 'original.webm'); assert.equal(await file.failure(), null);
    await page.getByRole('button', { name: 'Today', exact: true }).click();
    await page.getByRole('button', { name: 'The perfect moment', exact: true }).waitFor();
    await mkdir('artifacts', { recursive: true });
    await capture('desktop.png');
    await page.setViewportSize({ width: 390, height: 844 });
    await capture('mobile.png');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, 'No mobile horizontal overflow');
    await page.getByRole('button', { name: `${target}, 1 clips`, exact: true }).tap({ force: true }).catch(async () => page.getByRole('button', { name: `${target}, 1 clips`, exact: true }).click());
    await page.getByRole('button', { name: 'Another day’s edit', exact: true }).waitFor();
    await page.setViewportSize({ width:1440,height:1000 });
    await page.getByRole('button',{name:'My stats',exact:true}).click();
    await page.getByTestId('total-clips').waitFor();
    assert.equal(await page.getByTestId('total-clips').innerText(),'2clips');
    assert.equal(await page.getByRole('heading',{name:'Team contributions',exact:true}).count(),0);
    await page.getByRole('button',{name:'Sign out',exact:true}).click();
    await page.getByLabel('Email address').fill('owner@example.com');
    await page.getByLabel('Password',{exact:true}).fill('a-long-test-password');
    await page.getByRole('button',{name:'Sign in',exact:true}).click();
    await page.getByRole('heading',{name:'The clip library',exact:true}).waitFor();
    await page.getByRole('button',{name:'The perfect moment',exact:true}).click();
    await page.locator('.review-form').waitFor();
    await capture('review-desktop.png');
    await audit('Review');
    await page.getByLabel('Review status').selectOption('approved');
    await page.getByLabel('Posting tag').selectOption('personal');
    await page.getByLabel('Feedback for the clipper').fill('Great cut. Ready for the page.');
    await page.getByRole('button',{name:'Save review',exact:true}).click();
    await page.getByText('Review saved. The clipper can see your feedback.').waitFor();
    await page.getByRole('button',{name:'Close dialog',exact:true}).click();
    await page.locator('.media-card').filter({has:page.getByRole('button',{name:'The perfect moment',exact:true})}).getByText('Ima post',{exact:true}).waitFor();
    await page.getByRole('button',{name:'The perfect moment',exact:true}).click();
    assert.equal(await page.getByLabel('Posting tag').inputValue(),'personal');
    await page.getByLabel('Posting tag').selectOption('clip_page');
    await page.getByRole('button',{name:'Save review',exact:true}).click();
    await page.getByRole('button',{name:'Save review',exact:true}).waitFor();
    await page.getByRole('button',{name:'Close dialog',exact:true}).click();
    await page.getByLabel('Filter clips by status').selectOption('tag:clip_page');
    assert.equal(await page.locator('.media-card').count(),1);
    await page.getByLabel('Filter clips by status').selectOption('all');
    await page.getByRole('button',{name:'The perfect moment',exact:true}).click();
    await page.getByLabel('Review status').selectOption('not_posting');
    assert.equal(await page.getByLabel('Posting tag').inputValue(),'');
    assert.equal(await page.getByLabel('Posting tag').isDisabled(),true);
    await page.getByLabel('Feedback for the clipper').fill('');
    await page.getByRole('button',{name:'Save review',exact:true}).click();
    assert.equal(await page.getByLabel('Feedback for the clipper').evaluate(e=>e.validity.valueMissing),true);
    await page.getByLabel('Feedback for the clipper').fill('The audio needs another pass.');
    await page.getByRole('button',{name:'Save review',exact:true}).click();
    await page.getByRole('button',{name:'Save review',exact:true}).waitFor();
    await page.getByRole('button',{name:'Close dialog',exact:true}).click();
    await page.getByLabel('Filter clips by status').selectOption('not_posting');
    await page.getByRole('button',{name:'Read note for The perfect moment',exact:true}).waitFor();
    await page.setViewportSize({width:390,height:844});
    await page.getByRole('button',{name:'The perfect moment',exact:true}).click();
    await audit('Mobile posting notes');
    await page.screenshot({path:'artifacts/posting-notes-mobile.png',fullPage:true});
    await page.getByRole('button',{name:'Close dialog',exact:true}).click();
    await page.setViewportSize({width:1440,height:1000});
    await page.getByLabel('Filter clips by status').selectOption('all');
    for(let i=0;i<18;i++) {
      const d=new Date(`${today}T12:00:00`); d.setDate(d.getDate()-Math.floor(i*1.3));
      const day=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
      const added=await page.request.post('/api/clips',{ multipart:{ title:`Review fixture ${i+1}`, day, video:{name:'original.webm',mimeType:'video/webm',buffer:Buffer.from(video)} } });
      assert.equal(added.status(),201); const id=(await added.json()).id;
      if(i%4!==0) await page.request.patch(`/api/clips/${id}`,{data:{status:i%3===0?'posted':'approved'}});
    }
    await page.getByRole('button',{name:'Refresh workspace',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('.nav-count')?.textContent==='20');
    await page.getByRole('button',{name:'Analytics',exact:true}).click();
    await page.getByRole('heading',{name:'Team contributions',exact:true}).waitFor();
    assert.equal(await page.getByTestId('total-clips').innerText(),'20clips');
    const csvPromise=page.waitForEvent('download');
    await page.getByRole('button',{name:'Export CSV',exact:true}).click();
    const csv=await csvPromise; assert.match(csv.suggestedFilename(),/orangie-daily-.*\.csv/);
    await page.getByRole('button',{name:'7 days',exact:true}).click();
    await page.waitForFunction(()=>!document.querySelector('.stats-content')?.classList.contains('updating'));
    assert.equal(await page.locator('.bar-column').count(),7);
    await page.getByRole('button',{name:'30 days',exact:true}).click();
    await page.waitForFunction(()=>document.querySelectorAll('.bar-column').length===30);
    await page.locator('.bar-column').first().click();
    await page.getByText('No clips were added to this date. Select another bar above.').waitFor();
    await capture('analytics-desktop.png');
    await audit('Analytics');
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'Analytics fits mobile');
    await capture('analytics-mobile.png');
    await page.setViewportSize({width:1440,height:1000});
    await page.getByRole('button',{name:'The team',exact:true}).click();
    await page.getByRole('button',{name:'Manage Sam',exact:true}).waitFor();
    await capture('team-desktop.png');
    await audit('Team');
    await page.getByRole('button',{name:'Manage Sam',exact:true}).click();
    await page.getByLabel('Role',{exact:true}).selectOption('team');
    await page.getByRole('button',{name:'Save access',exact:true}).click();
    await page.getByText('Member access updated. Previous sessions have been signed out.').waitFor();
    await page.getByRole('navigation').getByRole('button',{name:'Clip library',exact:false}).click();
    await page.getByRole('button',{name:'Today',exact:true}).click();
    await capture('desktop.png');
    await audit('Library');
    await page.getByRole('button',{name:'Sign out',exact:true}).click();
    await page.getByLabel('Email address').fill('maya@example.com');
    await page.getByLabel('Password',{exact:true}).fill('maya-test-password');
    await page.getByRole('button',{name:'Sign in',exact:true}).click();
    await page.getByRole('heading',{name:'The clip library',exact:true}).waitFor();
    await page.getByRole('button',{name:'The team',exact:true}).click();
    await page.getByRole('heading',{name:'Workspace members',exact:false}).waitFor();
    assert.equal(await page.getByRole('button',{name:'Add member',exact:true}).count(),1);
    assert.equal(await page.getByRole('button',{name:'Manage Sam',exact:true}).count(),1);
    await page.getByRole('navigation').getByRole('button',{name:'Clip library',exact:false}).click();
    await page.getByRole('button',{name:'Today',exact:true}).click();
    await page.getByRole('button',{name:'The perfect moment',exact:true}).click();
    await page.getByLabel('Review status').selectOption('approved');
    await page.getByLabel('Posting tag').selectOption('clip_page');
    await page.getByLabel('Feedback for the clipper').fill('Team checked the audio. Ready for the clip page.');
    await page.getByRole('button',{name:'Save review',exact:true}).click();
    await page.getByRole('button',{name:'Save review',exact:true}).waitFor();
    await page.getByRole('button',{name:'Close dialog',exact:true}).click();
    await page.getByRole('button',{name:'Read note for The perfect moment',exact:true}).waitFor();
    assert.deepEqual(errors, []);
  } finally { await browser?.close(); await server.close(); }
});
