import React, { useEffect, useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, BarChart3, CalendarDays, ChevronRight, Film, HardDrive, Users } from 'lucide-react';
import { api, bytes, dateOf, downloadCSV, formatDate, localDay, shiftDay, statusLabels } from './lib';
import { Status } from './components';

export default function Analytics({ user, refreshKey, openDay, openClip, clips }) {
  const [range, setRange] = useState({ from: shiftDay(localDay(), -29), to: localDay() }); const [preset, setPreset] = useState('30');
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState(localDay());
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError('');
    api(`/analytics?from=${range.from}&to=${range.to}`, { signal: controller.signal }).then(d => { setData(d); setSelected(s => s < range.from || s > range.to ? range.to : s); }).catch(e => { if (e.name !== 'AbortError') setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [range.from, range.to, refreshKey]);
  function period(value) { setPreset(value); if (value !== 'custom') setRange({ from: shiftDay(localDay(), 1 - Number(value)), to: localDay() }); }
  function exportDaily() { downloadCSV(`orangie-daily-${data.from}-${data.to}.csv`, [['Date','Clips','Contributors','Original bytes','To review','Approved','Changes needed','Posted'], ...data.daily.map(d => [d.day,d.clips,d.contributors,d.bytes,d.pending,d.approved,d.changes,d.posted])]); }
  const own = !user.permissions.teamStats;
  if (!data && !error) return <div className="stats-loading" role="status"><div/><div/><div/><p>Loading your upload statistics...</p></div>;
  const totals = data?.totals; const currentDay = data?.daily.find(d => d.day === selected); const selectedClips = clips.filter(c => c.day === selected);
  const change = totals ? totals.clips - data.previous.clips : 0;
  const max = Math.max(1, ...(data?.daily.map(d => d.clips) || []));
  return <div className="analytics-page"><div className="analytics-controls"><div className="segmented" aria-label="Statistics period">{[['7','7 days'],['30','30 days'],['90','90 days'],['custom','Custom']].map(([v,label]) => <button key={v} aria-pressed={preset === v} className={preset === v ? 'active' : ''} onClick={() => period(v)}>{label}</button>)}</div><div className="range-inputs"><label><span className="sr-only">From date</span><input type="date" aria-label="From date" value={range.from} max={range.to} onChange={e => { if (e.target.value) { setPreset('custom'); setRange(r => ({ ...r, from: e.target.value })); } }}/></label><span>to</span><label><span className="sr-only">To date</span><input type="date" aria-label="To date" min={range.from} value={range.to} onChange={e => { if (e.target.value) { setPreset('custom'); setRange(r => ({ ...r, to: e.target.value })); } }}/></label></div><button className="button export-button" onClick={exportDaily} disabled={!data || loading || Boolean(error)}><ArrowDownToLine size={15}/>Export CSV</button></div>
    {error && <p className="error" role="alert">{error}</p>}
    {data && !error && <div className={loading ? 'stats-content updating' : 'stats-content'} aria-busy={loading}><div className="metrics-strip"><div className="metric"><span><Film size={16}/>{own ? 'Your clips' : 'Clips delivered'}</span><strong data-testid="total-clips">{totals.clips}<small>clips</small></strong><p className={change > 0 ? 'positive' : ''}>{change > 0 ? '+' : ''}{change} vs previous {data.daily.length} days</p></div><div className="metric"><span><Users size={16}/>{own ? 'Days you uploaded for' : 'Active contributors'}</span><strong>{own ? totals.activeDays : totals.contributors}<small>{own ? 'days' : 'people'}</small></strong><p>{own ? `${data.daily.length} days in this period` : `${data.members.filter(m => m.active).length} active workspace members`}</p></div><div className="metric"><span><BarChart3 size={16}/>Approved or posted</span><strong>{totals.approved + totals.posted}<small>clips</small></strong><p>{data.approvalRate === null ? 'No clips in this period' : `${Math.round(data.approvalRate)}% of clips in this period`}</p></div><div className="metric"><span><HardDrive size={16}/>Original files added</span><strong className="size-metric">{bytes(totals.bytes)}</strong><p>{bytes(data.allTime.bytes)} across all time</p></div></div>
    <div className="analytics-grid"><section className="chart-panel"><div className="section-heading"><div><h2>Daily delivery</h2><p>{formatDate(data.from)} - {formatDate(data.to, { month: 'short', day: 'numeric', year: 'numeric' })}</p></div><span className="chart-average">{data.averagePerDay.toFixed(1)}<small>clips / day</small></span></div><div className="chart-layout"><div className="chart-y"><span>{max}</span><span>{Math.round(max / 2)}</span><span>0</span></div><div className="chart-scroll"><div className="bar-chart" style={{ minWidth: `${Math.max(240, data.daily.length * 15)}px` }} aria-label="Clips per assigned date">{data.daily.map((d, i) => <button key={d.day} className={`bar-column ${selected === d.day ? 'selected' : ''}`} onClick={() => setSelected(d.day)} aria-label={`${formatDate(d.day)}, ${d.clips} clips`} aria-pressed={selected === d.day}><span className="bar-tooltip">{formatDate(d.day)}<strong>{d.clips} {d.clips === 1 ? 'clip' : 'clips'}</strong></span><span className={`chart-bar ${d.clips ? '' : 'zero'}`} style={{ height: `${d.clips / max * 100}%` }}/><span className="bar-label">{i === 0 || i === data.daily.length - 1 || i % Math.max(1, Math.ceil(data.daily.length / 7)) === 0 ? dateOf(d.day).getDate() : ''}</span></button>)}</div></div></div><div className="chart-caption"><span><span className="legend-square"/>Clips added to each date</span><span>Choose a bar to inspect a day</span></div></section><section className="workflow-panel"><div className="section-heading"><div><h2>Where things stand</h2><p>Current status of this period’s clips</p></div></div><div className="workflow-total"><strong>{totals.pending}</strong><span>waiting for review</span></div><div className="status-stack">{Object.entries(statusLabels).map(([s,label]) => <div key={s}><span className={`status-indicator ${s}`}/><span>{label}</span><strong>{totals[s]}</strong></div>)}</div><p className="workflow-footnote">Statuses are updated by Orangie and Team members.</p></section></div>
    <section className="daily-detail"><div className="section-heading"><div><h2><CalendarDays size={18}/>{formatDate(selected, { weekday: 'long', month: 'long', day: 'numeric' })}</h2><p>{currentDay?.clips || 0} clips · {currentDay?.contributors || 0} contributors · {bytes(currentDay?.bytes || 0)}</p></div><button className="button" onClick={() => openDay(selected)}>Open in library<ArrowUpRight size={15}/></button></div>{selectedClips.length ? <div className="day-detail-clips">{selectedClips.map(c => <button key={c.id} onClick={() => openClip(c)}><span className="detail-file-icon"><Film size={18}/></span><span><strong>{c.title}</strong><small>{c.creator} · {bytes(c.size)}</small></span><Status status={c.status}/><ChevronRight size={15}/></button>)}</div> : <div className="daily-empty">No clips were added to this date. Select another bar above.</div>}</section>
    {!own && <section className="contribution-panel"><div className="section-heading"><div><h2>Team contributions</h2><p>Delivery and review status for every member in this period.</p></div><button className="text-button" onClick={() => downloadCSV(`orangie-team-${data.from}-${data.to}.csv`, [['Member','Role','Clips','Active days','Original bytes','To review','Approved','Changes needed','Posted'], ...data.members.map(m => [m.name,m.role,m.clips,m.activeDays,m.bytes,m.pending,m.approved,m.changes,m.posted])])}><ArrowDownToLine size={14}/>Export team</button></div><div className="table-scroll"><table><thead><tr><th>Contributor</th><th>Clips</th><th>Active days</th><th>Approved / posted</th><th>Original files</th><th>Share</th></tr></thead><tbody>{data.members.map(m => <tr key={m.id}><td><div className="table-person"><span className="avatar">{m.name[0]}</span><span><strong>{m.name}</strong><small>{m.role}{!m.active ? ' · Disabled' : ''}</small></span></div></td><td className="number-cell">{m.clips}</td><td>{m.activeDays}</td><td>{m.approved + m.posted}</td><td>{bytes(m.bytes)}</td><td><div className="contribution-share"><span>{totals.clips ? Math.round(m.clips / totals.clips * 100) : 0}%</span><div><i style={{ width: `${totals.clips ? m.clips / totals.clips * 100 : 0}%` }}/></div></div></td></tr>)}</tbody></table></div></section>}
    <p className="stats-note">Statistics use each clip’s assigned calendar date and current review status. All-time totals cover {own ? 'your uploads' : 'the workspace'}. Social views and playback are not tracked.</p></div>}
  </div>;
}
