import React, { useState } from 'react';
import { ArrowDownToLine, Check, MessageSquare, ShieldCheck } from 'lucide-react';
import { api, bytes, formatDate, statusLabels, postingLabels } from './lib';
import { Modal, Status } from './components';
export default function ClipPreview({ clip, user, close, saved }) {
  const [postingTag,setPostingTag]=useState(clip.posting_tag||'');
  const [status,setStatus]=useState(clip.status); const [note,setNote]=useState(clip.review_note||''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function review(e) { e.preventDefault();setBusy(true);setError('');try{await api(`/clips/${clip.id}`,{method:'PATCH',body:JSON.stringify({status,review_note:note,posting_tag:postingTag})});saved({...clip,status,review_note:note.trim(),posting_tag:postingTag});}catch(e){setError(e.message);}finally{setBusy(false);} }
  return <Modal title={clip.title} close={close} wide><div className="review-studio"><div className="review-screen"><video className="preview-player" controls autoPlay playsInline src={`/api/clips/${clip.id}/preview`}/><div className="review-screen-footer"><span><ShieldCheck size={14}/>Original file</span><span>{clip.original_name.split('.').pop().toUpperCase()} · {bytes(clip.size)}</span></div></div><aside className="review-side"><div className="review-author"><span className="avatar">{clip.creator[0]}</span><div><strong>{clip.creator}</strong><small>{formatDate(clip.day,{month:'long',day:'numeric'})}</small></div><Status status={clip.status}/></div><a className="button primary review-download" href={`/api/clips/${clip.id}/download`} download><ArrowDownToLine size={17}/>Download original</a><div className="review-note-heading"><MessageSquare size={16}/><h3>{user.permissions.reviewClips?'Posting plan & notes':'Feedback from the team.'}</h3></div>{user.permissions.reviewClips?<form className="review-form" onSubmit={review}><div className="review-fields"><label>Review status<select aria-label="Review status" value={status} onChange={e=>{setStatus(e.target.value);if(e.target.value==='not_posting')setPostingTag('');}}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Posting tag<select aria-label="Posting tag" value={postingTag} disabled={status==='not_posting'} onChange={e=>setPostingTag(e.target.value)}><option value="">No tag yet</option>{Object.entries(postingLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Feedback for the clipper<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} required={status==='changes'||status==='not_posting'} placeholder={status==='not_posting'?'Why are you passing on this clip?':'Add a note for the clipper...'} rows={5}/><small className="note-help">{status==='not_posting'?'A reason is required. ':''}Orangie and Team can edit this shared note. The clipper can read it.</small></label></div>{error&&<p className="error" role="alert">{error}</p>}<button className="button" disabled={busy}><Check size={16}/>{busy?'Saving...':'Save review'}</button></form>:<div className="clip-feedback">{clip.posting_tag&&<span className="posting-tag">{postingLabels[clip.posting_tag]}</span>}<p>{clip.review_note||'No feedback yet. Review notes will appear here.'}</p></div>}<p className="preview-note">If this video cannot play in your browser, download the original. The Posted status records a post; it does not publish it.</p></aside></div></Modal>;
}
